version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nx:
        patterns: ['nx', '@nx/*']
      nestjs:
        patterns: ['@nestjs/*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/frontend
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/client-api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/action-log-service
    schedule:
      interval: weekly
