services:
  frontend:
    container_name: frontend
    image: ${DOCKER_IMAGE_REPOSITORY:-argsoftware/nx-template}:${FRONTEND_IMAGE_TAG:-frontend-0.0.21}
    environment:
      - PORT=80
      - HOSTNAME=0.0.0.0
    ports:
      - '80:80'
    networks:
      - nx-template
    depends_on:
      - client-api

  client-api:
    container_name: client-api
    image: ${DOCKER_IMAGE_REPOSITORY:-argsoftware/nx-template}:${CLIENT_API_IMAGE_TAG:-client-api-0.0.20}
    env_file:
      - path: ./env/.env.apps.common
        required: true
      - path: ./env/.env.apps.api
        required: true
    ports:
      - '3333:3333'
    networks:
      - nx-template

  action-log-service:
    container_name: action-log-service
    image: ${DOCKER_IMAGE_REPOSITORY:-argsoftware/nx-template}:${ACTION_LOG_IMAGE_TAG:-action-log-service-0.0.8}
    env_file:
      - path: ./env/.env.apps.common
        required: true
      - path: ./env/.env.apps.action-log
        required: true
    ports:
      - '3334:3334'
    networks:
      - nx-template

networks:
  nx-template:
    name: nx-template
    driver: bridge
    external: true
