name: version and deploy on commit into main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  version-and-deploy-on-commit-into-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - name: Configure Git identity
        run: |
          git config --global user.email ${{ vars.EMAIL }}
          git config --global user.name ${{ vars.USERNAME }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ARG-Software/nx-template.git

      - name: Run Publish for Affected Projects
        run: |
          npm run docker:publish:affected
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
